version: 2

models:
  - name: dim_customers
    description: "Dimension table containing unique customer records."
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique
      - name: email
        tests:
          - not_null

  - name: fct_loans
    description: "Incrementally loaded fact table capturing approved loans and related metrics."
    columns:
      - name: loan_id
        tests:
          - not_null
          - unique
      - name: customer_id
        tests:
          - relationships:
              to: ref('dim_customers')
              field: customer_id
      - name: start_date
        tests:
          - not_null
          
  - name: dim_dates
    description: "Calendar dimension providing derived time attributes."
    columns:
      - name: date_actual
        tests:
          - not_null
          - unique

  - name: fct_payments
    description: "Fact table containing all loan payment transactions."
    columns:
      - name: payment_id
        tests:
          - not_null
          - unique
      - name: loan_id
        tests:
          - relationships:
              to: ref('fct_loans')
              field: loan_id
